### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by csweetj** [csweetj/furima-29067#10]
# フリマアプリURL
https://furima-29067.herokuapp.com/
# Basic認証IDとパスワード
ID：admiin
password：2222
# 出品者用のメールアドレスとパスワード
email：sample@sample.com
password：123abc
# 購入者用のメールアドレスとパスワード
email：sample2@sample.com
password：123abc
# カードの番号・期限・セキュリティコード
card_number：4242424242424242
expiration_date：04/24
cvc：123

**Comment by MasaakiTanabashi** [comment]
常さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◎出品した商品の削除が行なえません。
出品者が出品した商品を削除しようとすると、削除ができず「We're sorry...」が表示されます。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by csweetj** [comment]
ご確認ありがとうございます！
確認したらdestroyのスペルミスでした

**Comment by kaho0919** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

LGTMですが、若干気になったところがあったので、確認し、修正お願いします。
・トップページの出品商品の写真の周辺のビューが重なっていたりして少し崩れています。
**※実装はOKですので、コチラは再度提出なしでいいです。**

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
